baseURL = "https://rycollins.com/"
languageCode = "en-us"
title = "Ry Collins"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Ry Collins"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Blog"
copyright = "Copyright © 2018 Ryan Collins"
logofile = ""
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "rymcol"
#email = ""
linkedin = "rymcol"
twitter = "rymcol"
#social_banner = "img/banner.png"
#posts_navigation = true
small_banner_logo = false
